### ISSUE TITLE
Respect current shuffle setting

### ISSUE THREAD

**Issue by caleb531** [caleb531/play-song#35]
Hi, @Tyilo. I have an idea for Play Song that I'd like to discuss with you.

Currently, Play Song forcefully disable shuffle mode before playing its queue in iTunes. This ensures that albums/playlists *always* play in the correct order. However, I am beginning to realize that forcefully disabling shuffle was not the best approach when I initially wrote v2.0. Therefore, I propose that we update the workflow to respect the current shuffle setting for the following reasons:

1. Play Song would no longer require access to assistive devices
2. Some iTunes users prefer to *always* or *sometimes* play albums/playlists on shuffle
3. Play Song cannot disable shuffle for non-English systems anyway (recall issue #24)

As always, I welcome your feedback before I proceed to implement this.

**Comment by Tyilo** [comment]
I never use the shuffle functionality myself, but I agree with you and think you should go for it ;)
