### ISSUE TITLE
playplaylist does not list any playlists (Alfred 3.0 version)

### ISSUE THREAD

**Issue by dapperdanman1400** [caleb531/play-song#40]
When I try to use the `playplaylist` command, it doesn't list any playlists, it just gives me web browser search options.

**Comment by caleb531** [comment]
Hi, @dapperdanman1400. I'll try to help you as best as I can, so I'd like to start by asking a few questions:

1. What version of Alfred are you using?
2. Do any other filters like `playsong` work for you?
3. How many playlists do you have in iTunes? (besides the Alfred Play Song playlist)

Thanks,
Caleb

**Comment by dapperdanman1400** [comment]
1. Yes, all of the filters except `playplaylist` are working for me.
2. I have 2 playlists, one of which is a smart playlist (don't know if that matters).

**Comment by caleb531** [comment]
Can you please open up the [Workflow Debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/) (the insect-looking icon) for Play Song and then search with `playplaylist` once more? It would seem some error is being thrown that is preventing Play Song from showing any results.

**Comment by dapperdanman1400** [comment]
[2016-06-11 11:49:54][ERROR: input.scriptfilter] Code 1: 1823:1865: execution error: iTunes でエラーが起きました：quantifyNumber を続けることができません。 (-1708)

Sorry, it's in Japanese. It says something along the lines of:
"An iTunes error has occurred: cannot continue quantifyNumber."

**Comment by caleb531** [comment]
I just realized that `playplaylist` doesn't work for me, either (I don't really use playlists, so I never search with `playplaylist`); I can't believe I never noticed. Fortunately, I have found the cause of the issue and will push a fix momentarily.

Stand by...

**Comment by caleb531** [comment]
Alright, @dapperdanman1400, I've pushed the patched workflow (v4.0.1). Please let me know if this also solves the issue for you. :)

**Comment by dapperdanman1400** [comment]
Works great now! Thanks!
