### ISSUE TITLE
Play any song without using alfred playlist (iTunes resumes on existing playlist)

### ISSUE THREAD

**Issue by kevinjalbert** [caleb531/play-song#42]
I had used an old version of this plugin (version 2.x?) and it had the capabilities of `play`ing any song within itunes immediately and then itunes would continue on where it left off. This was a great workflow for me as sometimes I would just want to hear a specific song, and afterwards itunes would continue playing in the manner it was before (i.e., in a playlist).

I had updated to the latest version and noticed songs can be queued up and would placed in an alfred playlist. The issue here is when the song would finish itunes wouldn't go back to the old playlist.

I'm just putting this out here but this the new action I put for `playsong`

```applescript
on loadConfig()
	return (load script POSIX file (do shell script "./resources/compile-config.sh"))
end loadConfig

on run query
	set config to loadConfig()
	
	set typeAndId to parseResultQuery(query as text) of config
	set theType to type of typeAndId
	set theId to id of typeAndId

	set theSong to getSong(theId) of config
	
	log theSong

    tell application "iTunes" to play theSong
end run
```

Essentially I just want to tell iTunes to play the selected song. No playlist stuff to worry about and modify.

@caleb531 you can close this if you want. I was just putting this up as it was something that had existed in the past, just incase someone stumbles upon they can use this custom action. If its something you see benefit in having as an alternative action (i.e., `alt` for `playsong`) that works as well.

**Comment by cantsingh** [comment]
Wow, @kevinjalbert- thank you so much for this. I had just been in contact with @caleb531 about this very functionality. You helped me, if nobody else!

**Comment by caleb531** [comment]
Thank you very much for your contribution, @kevinjalbert. Yes, I have indeed been discussing this with @cantsingh—I shared with him my rationale for the behavior change, which I will repost below for your benefit:

> The behavior is in part an iTunes limitation and a architectural choice with how I wanted to design Play Song. iTunes allows me to play a single song by itself (without playing it out of a playlist), which results in the old behavior you desire. However, the only way I can play multiple songs in succession is to play a playlist, yet other music will not resume playing after the playlist finishes (unless you set the playlist to Repeat All or something).

> Play Song v1 was limited to playing only individual songs. Therefore, one of my main goals for v2 was to allow for the playing of albums, artists, genres, etc., which was a heavily-requested feature. As mentioned, the only way I can play multiple songs is via a playlist, and for the sake of consistency, I decided to do the same for individual songs (as I can use the same function for playing anything via Play Song—songs, albums, artists, etc.). This much I do not plan to change.

After @cantsingh requested the return of the old behavior, I have been considering re-introducing the old behavior via a modifier key (like *option*) when filtering individual songs. Granted, this would *only* work for individual songs, and not albums, artists, genres, or even playlists.

@kevinjalbert, now that you have seconded the request to have the old behavior back, I am very tempted to do just that. @cantsingh told me he would be fine with the modifier-based approach I described above. Would that be an acceptable solution for you also? (FWIW, modifying the workflow to make the modifier behavior the default would be quite easy to do on your own, if that's what you really want).

Regards,
Caleb

**Comment by kevinjalbert** [comment]
@cantsingh glad that it helped you out :)

-----

@caleb531 I think adding the old behaviour as through the _option/alt_ modifier key wouldn't be a bad idea. From what I see there is a free modifier key open for the `playsong` trigger.

Like you mentioned, it is easy enough to add the desired functionality on our own (which is my current setup).  It wouldn't hurt having it baked in though so we can take advantage of updates more easily. Either way, in my case I'm still going to modify the workflow so that the non-modifier selection is to play the individual song without a playlist (old behaviour).

**Comment by caleb531** [comment]
I see. @cantsingh, is the old behavior via modifier sufficient enough for you, or would you also modify the workflow to make it the default (like @kevinjalbert)?

**Comment by cantsingh** [comment]
Haha, I've actually already modified my local version of @caleb531 's workflow to only have the playsong query and make it the default. Personally, I never used the other functionalities of the workflow, so it made more sense for me to make @kevinjalbert 's implementation the default.

**Comment by caleb531** [comment]
Well, I have no desire to make the old behavior the default, as it's completely inconsistent with every other Play Song feature (as I've stated in my above rationale). In truth, adding the old behavior via modifier key is largely a concession to both of you, and I only wish to add it if you actually intend to use it, *or* at least if it makes modifying the workflow considerably easier. What do you each think?

**Comment by kevinjalbert** [comment]
As mentioned before I would be fine with it being added as a modifier since I can then have an easier update process with this workflow. I still would personally change the default behaviour, but that would now be as easy as moving connectors around in the Alfred workflow editor.

**Comment by caleb531** [comment]
Fair enough. Unfortunately, I tried setting up the `alt` (*i.e.* `option`) binding in the workflow editor, but for some strange reason, the action script would not run when I choose any song via the *option* key. It seems to work with other modifiers—just not `alt`. Can you confirm this?

**Comment by kevinjalbert** [comment]
@caleb531 yep I'm seeing the same thing... Might be an Alfred problem? With `alt` it didn't work, but with `shift` it would. Really quite odd. For me it was still invoking the old behaviour where it would play the song after queuing it up in a playlist.

**Comment by caleb531** [comment]
According to my testing, it's not an Alfred issue—it's an iTunes behavior (I would call it a bug).

It seems that if the alt/option key is held down when AppleScript calls the `play` command, the track will queue in Up Next and not play at all. Otherwise, the track plays immediately.

Here's an AppleScript to demonstrate this (change the track name to a track in your library, of course).

```applescript
tell application "iTunes"
	
	-- give you time hold down alt/option modifier
	delay 2
	
	play track "Zadok the Priest"
	-- track plays if alt/option modifier is not held down
	-- track is queued in Up Next (but doesn't play) if alt/option modifier is held down
	
end tell
```

**Comment by kevinjalbert** [comment]
@caleb531 interesting behaviour. I guess its `shift` (I think that is all thats left?) or we just ignore this request.

**Comment by caleb531** [comment]
@kevinjalbert I'm fine with binding the behavior to `shift`. In fact, I have just pushed a new [feature-v1-behavior](https://github.com/caleb531/play-song/tree/feature-v1-behavior) branch which implements the addition. Granted, I wanted to ask before your final feedback before I commit the exported workflow, and so I've attached the beta below. Please let me know if it's to your liking, or if you have any suggestions (besides making it the default behavior for songs—I'm still opposed to that). :P

Regards,
Caleb

[Play Song v4.3.0-beta.1.alfredworkflow.zip](https://github.com/caleb531/play-song/files/511986/Play.Song.v4.3.0-beta.1.alfredworkflow.zip)

**Comment by kevinjalbert** [comment]
@caleb531 Works as expected 👍 .

I'll be switching the modifiers around to suit my needs, but at least its all in the workflow now.

**Comment by caleb531** [comment]
@kevinjalbert I figured. ;)

I'll commit the workflow and push a new release in a few days.
