### ISSUE TITLE
can't find songs, albums, artists (can only find playlists)

### ISSUE THREAD

**Issue by nikitavoloboev** [caleb531/play-song#44]
Is there anything I can do to fix this?

**Comment by caleb531** [comment]
Can you please be more specific? Do you mean to say that `playartist`, `playalbum`, *etc.* show no results, but `playplaylist` is? Could you please post a screenshot of what you are seeing?

Thanks,
Cakeb

**Comment by nikitavoloboev** [comment]
Yes you are right.

Here is an example : 
![2016-10-09 at 22 44](https://cloud.githubusercontent.com/assets/6391776/19223506/e80e1eee-8e71-11e6-9515-d8fdf4ff01c8.png)

And the result : 

![2016-10-09 at 22 44](https://cloud.githubusercontent.com/assets/6391776/19223507/f6f5ce66-8e71-11e6-9ea0-e8f34fdeaab6.png)

Nothing found, yet I have the song.

Thank you for any help.

**Comment by caleb531** [comment]
What Play Song version are you using? And by your screenshot, it looks like you've renamed the `playsong` filter to `ps`, correct? And if so, what other changes have you made to your installed version of the workflow?

Thanks,
Caleb

**Comment by nikitavoloboev** [comment]
I got the most recent version, from your releases on GitHub (4.2.1). 

Haven't made any other changes I think aside from chasing the name for the trigger.

**Comment by caleb531** [comment]
I see. I suspect that Play Song is throwing an error, considering that not even the "No Results Found" result is showing. Can you please open the Alfred debugger for Play Song and run the workflow again, pasting any error messages here?

**Where to find debugger:**  
![screen shot 2016-10-09 at 2 11 58 pm](https://cloud.githubusercontent.com/assets/872474/19223688/97daff10-8e2a-11e6-887d-dc268cda61d6.png)

**Comment by nikitavoloboev** [comment]
Here is the error I get when running play song : 

![2016-10-12 at 00 08](https://cloud.githubusercontent.com/assets/6391776/19290456/157cb3e6-9010-11e6-93a5-3ab0174e0c5b.png)

Other actions also send this error code.

**Comment by caleb531** [comment]
Hmm, interesting. What versions of OS X and iTunes are you using?

**Comment by nikitavoloboev** [comment]
El Captain latest. Can't update to Sierra yet.

**Comment by caleb531** [comment]
Great! And what about your iTunes version? :)

**Comment by nikitavoloboev** [comment]
Here it is : 
![2016-10-12 at 11 15](https://cloud.githubusercontent.com/assets/6391776/19304497/3cfe8932-906d-11e6-9cb3-da4adc4f360e.png)

**Comment by caleb531** [comment]
I see—how strange. Alright, I need your help with some testing so we can hunt down and destroy this bug once and for all.

Attached below is a ZIP file containing «an AppleScript compiled from a large chunk the Play Song source code. Please extract the ZIP file and open the script in the *Script Editor* app (it may open in Script Editor by default, otherwise it's in under `/Applications/Utilities`).

[Test Everything.zip](https://github.com/caleb531/play-song/files/530404/Test.Everything.zip)

For me, this code runs fine, and the script returns some songs. For you, you should receive the same error you saw in Alfred's Debugger panel. However, the Script Editor should highlight the line where that error occurred, and *that* is what I want you to post here (screenshot is preferable).

Please let me know what you find, or if you have any questions.

Thanks,
Caleb

**Comment by nikitavoloboev** [comment]
![2016-10-14 at 23 25](https://cloud.githubusercontent.com/assets/6391776/19403176/917eaee8-9265-11e6-92a7-c331ed9d6b1e.png)

There you go :)

**Comment by caleb531** [comment]
Oh, interesting. Can you please add the following line above that line like so?

```applescript
log theSong
set songArtwork to data of (item 1 of songArtworks)
```

Then, run the entire script again and paste the results here. The log output should be under the Log icon (third icon on bottom) > **Messages**:

![screen shot 2016-10-14 at 2 28 00 pm](https://cloud.githubusercontent.com/assets/872474/19403230/95a23a58-921a-11e6-82e9-d3f66611b3c5.png)

**Comment by nikitavoloboev** [comment]
![2016-10-14 at 23 47](https://cloud.githubusercontent.com/assets/6391776/19403593/91536cb2-9268-11e6-9ed2-05283c7e8c42.png)

**Comment by caleb531** [comment]
Hmm, now can you please change `log theSong` to `log (kind of theSong)`? Also, directly below that line, please add another line: `log songArtworks`. Post the results when you've done all that.

Thanks for your patience—I want to fix this bug at least as much as you do. :)

**Comment by nikitavoloboev** [comment]
![2016-10-15 at 21 35](https://cloud.githubusercontent.com/assets/6391776/19412869/516f250c-931f-11e6-881e-1b10e3a0160d.png)

**Comment by caleb531** [comment]
Alright, that wasn't quite as useful as I was hoping. Please change `log (kind of theSong)` to `log ((kind of theSong) as text)` and post the new log output. Thanks!

**Comment by littleblue50** [comment]
Just letting you know I'm also having this exact problem

**Comment by caleb531** [comment]
@littleblue50, good to know. @nikitavoloboev, I haven't heard from you in a little over a month, but I still need your help testing this issue.

Thanks,
Caleb

**Comment by littleblue50** [comment]
If it helps though, when I run your test script I don't get an error, I just get:

`"{\"items\": [{\"uid\":\"no-results\",\"arg\":\"no-results\",\"valid\":\"no\",\"title\":\"No Results Found\",\"subtitle\":\"No songs matching 'Link'\",\"icon\":{\"path\":\"resources/icon-noartwork.png\"}}]}"`

**Comment by caleb531** [comment]
@littleblue50: interesting, though if you're not receiving the same error as @nikitavoloboev, then your problem is probably worthy of a separate GitHub issue.

**Comment by caleb531** [comment]
@nikitavoloboev and @littleblue50,

I have just released Play Song v5, which includes a bug fix that may resolve this error. Could you both please download and test it to see if anything has improved for you?

[Click to download Play Song v5](https://github.com/caleb531/play-song/raw/v5.0.0/Play%20Song%20(Alfred%203).alfredworkflow)

Thanks,
Caleb

**Comment by caleb531** [comment]
@nikitavoloboev and @littleblue50: I'm closing this issue because my testing has shown this issue is fixed by my patch above. If you are still experiencing problems, please let me know and I will reopen.
