### ISSUE TITLE
playartist, playalbum, etc. show no results, but playplaylist works fine

### ISSUE THREAD

**Issue by littleblue50** [caleb531/play-song#45]
Using the latest release version I get no results found for anything other than playplaylist.

**Comment by caleb531** [comment]
Hi, @littleblue50.

I have a few questions for you:

1. What is your system language set to?
2. Could you please provide some example queries you've tried? (including those that do and don't work)

**Comment by littleblue50** [comment]
Of course!

1) Japanese
2) Examples:

playplaylist Silent => works (although it finds some non-matching playlists and changes order of same results after every letter typed but it does find results)
playplaylist FF => works, caveat as above

playalbum The => no results found
playalbum Meteora => no results found

playartist Radiohead => no results found
playartist A => no results found

**Comment by caleb531** [comment]
In my experience, this is probably related to the fact that your system language is Japanese (and AppleScript, which Play Song is written in, gets a bit quirky when searching iTunes). What happens if you set your system language to English temporarily?

**Comment by littleblue50** [comment]
Changing the language to English does seem to solve the issue.  Is it not possible to use anything but playlist while in Japanese then?

**Comment by caleb531** [comment]
Unfortunately, that may be the case. Language Issues like this are likely an intrinsic issue with AppleScript or iTunes, rather than a bug in Play Song, which makes the issue practically impossible to fix on my part.
