### ISSUE TITLE
Cannot get track 1 of playlist 2 (for system language: Chinese)

### ISSUE THREAD

**Issue by BlasphemyAngels** [caleb531/play-song#47]
When I use the workflow, it didn't work. So I debug it, it occurred an error! 
![error](https://i.loli.net/2018/02/06/5a79643125bc5.png)

**Comment by caleb531** [comment]
@BlasphemyAngels Can you please post a screenshot of your query in the Alfred search box?

**Comment by caleb531** [comment]
@BlasphemyAngels Any update?

**Comment by caleb531** [comment]
Hi, @BlasphemyAngels.

I have implemented a possible fix for your issue, but I need you to test it to be sure. Please download the zipped workflow and let me know how things work for you (or if you receive any errors).

[Play Song v5.0.0-beta.5.alfredworkflow.zip](https://github.com/caleb531/play-song/files/2096361/Play.Song.v5.0.0-beta.5.alfredworkflow.zip)


Thanks,
Caleb

**Comment by caleb531** [comment]
@BlasphemyAngels,

I've just released Play Song v5, which (as another user has confirmed) fixes this issue. Therefore, I am closing this issue, but please let me know if you are still encountering problems with the new release.

Caleb
