### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [caleb531/play-song#50]
Hi @caleb531 ,I'm a graphic designer and an open source enthusiast. I would like to contribute to your project by proposing a logo design and I've designed a logo for you. If you like it you can use it. If you have an idea please share with me, it would be better for me. Thank you.
Best Regard.
![play song](https://user-images.githubusercontent.com/36124339/48308773-d0c50880-e59d-11e8-8aac-55eb61d94b6c.png)

**Comment by caleb531** [comment]
Thank you @mirzazulfan for your logo contributions. However, I don't prefer that Play Song have any logo—I actually prefer that the iTunes logo would be used, at least within the workflow (as this makes the UI clearer).
