### ISSUE TITLE
Allow songs search into Apple Music

### ISSUE THREAD

**Issue by NTag** [caleb531/play-song#52]
Hello,

It seems that `playsong [song title]` is only searching in my library. It would be great that for Apple Music subscribers, the search happens in Apple Music, so you could almost play every song that exists, and not only those you added to your library.

Very nice workflow by the way ;-) .

**Comment by caleb531** [comment]
@NTag Believe me, I've wanted to add this capability. Unfortunately, the iTunes AppleScript API does not expose any means of querying Apple Music—only your actual library. However, Play Song is able to play Apple Music playlists that you've added to your library, even if the individual songs haven't been added to your library.

<img width="968" alt="screen shot 2019-01-09 at 8 58 15 am" src="https://user-images.githubusercontent.com/872474/50915009-bddb8280-13ec-11e9-95ee-1e28ec057a4f.png">

<img width="559" alt="screen shot 2019-01-09 at 8 58 28 am" src="https://user-images.githubusercontent.com/872474/50915022-c5029080-13ec-11e9-87be-92f36c54ffd6.png">
