### ISSUE TITLE
Workflow fallback to search

### ISSUE THREAD

**Issue by planecore** [caleb531/play-song#54]
I cannot use this workflow because it always falls back to the regular Alfred search.

![Image](https://user-images.githubusercontent.com/12946462/56475867-27ad0300-6497-11e9-9e97-3d1ff12b0cd5.gif)

**Comment by caleb531** [comment]
@planecore Check the debug logs:

1. Open Alfred Preferences and navigate to the Play Song workflow under the _Workflows_ tab
2. Click the bug icon in the top-right corner, then try running `playsong` within Alfred again
3. Do you see any errors in the log panel?

**Comment by planecore** [comment]
Hi @caleb531 That's the output:

`[ERROR: input.scriptfilter] Code 1: filters/playsong.applescript:48:120: execution error: Can’t make file "Macintosh HD:Users:matan:Library:Caches:com.runningwithcrayons.Alfred-3:Workflow Data:com.calebevans.playsong:config.scpt" into type file. (-1700)`

**Comment by caleb531** [comment]
@planecore Thanks so much for reporting this—sounds like you've encountered the same issue as in #53. Fortunately, I believe I have found the cause of the issue. Please install this beta version of Play Song, and let me know if it fixes things:

[Play Song (Alfred 3).alfredworkflow.zip](https://github.com/caleb531/play-song/files/3101642/Play.Song.Alfred.3.alfredworkflow.zip)

Thanks,
Caleb

**Comment by planecore** [comment]
It works flawlessly now! Thanks :)
