### ISSUE TITLE
Support for OSX Catalina

### ISSUE THREAD

**Issue by andreifilip123** [caleb531/play-song#55]
Hello. 
Could you add support for Mac OS Catalina ?

**Comment by caleb531** [comment]
@andreifilip123 I will add support as soon as the stable version of Catalina is officially released. I will keep this issue open until I do so.

**Comment by caleb531** [comment]
@andreifilip123 I just wanted to let you know that I have upgraded my Mac, and have started work on adding Catalina support to Play Song. You can download the Beta version on my `catalina` branch:

https://github.com/caleb531/play-song/blob/catalina/Play%20Song%20-%20Catalina%20(Alfred%204).alfredworkflow

**Comment by andreifilip123** [comment]
I'll wait for the Alfred 3 workflow. Thanks tho :)

**Comment by caleb531** [comment]
@andreifilip123 Sorry to say, but the Catalina version of the workflow will only support Alfred 4. However, if you'd like, I can show you what changes you'd need to make to get your Alfred 3 version  of the workflow functional.

If you can export the Play Song workflow you currently have installed, and send it to me, I can send you back a custom version which supports Catalina.

**Comment by andreifilip123** [comment]
[Play Song.zip](https://github.com/caleb531/play-song/files/3727873/Play.Song.zip)

**Comment by andreifilip123** [comment]
Thanks 👍

**Comment by caleb531** [comment]
@andreifilip123 Alright, give this a shot. All the necessary code changes have been made, though I wasn't able to test it since I don't have Alfred 3 installed any longer.

[Play Song.alfredworkflow.zip](https://github.com/caleb531/play-song/files/3732190/Play.Song.alfredworkflow.zip)

Please let me know how this works for you.

**Comment by andreifilip123** [comment]
It doesn't seem to work. I can't import this. Thanks for the effort.

**Comment by caleb531** [comment]
@andreifilip123 Don't fret, I've given it another try—the import should be functional now. Please try the below version.

[PlaySong.alfredworkflow.zip](https://github.com/caleb531/play-song/files/3736123/PlaySong.alfredworkflow.zip)

**Comment by andreifilip123** [comment]
It works !!
Thanks a lot, man ! 👍 Really appreciate your efforts with this workflow. Thanks !

**Comment by raarellano** [comment]
Thanks for the Catalina update @caleb531  👏!
