### ISSUE TITLE
Queue isn't working?

### ISSUE THREAD

**Issue by zeltak** [caleb531/play-song#58]
Hi, first of all a huge thx this really is an incredible workflow!

>Queueing songs:For any of the above filters, choosing a result with the cmd key held down will queue the result (as opposed to playing it immediately).

it dosent seem to Abe working here ? Ii press `cmd` it does  show in alfred `queue song` but then i press enter (while CMD is pressed) it doesn't seem to queue.

on latest catalina and music app

would be happy to help debug

thx a bunch 

Z

**Comment by caleb531** [comment]
@zeltak Thanks for reaching out! What version of Play Song are you using? You can check by selecting the Play Song workflow in the Workflows area of Alfred Preferences.

![Screen Shot 2020-05-02 at 7 09 06 PM](https://user-images.githubusercontent.com/872474/80896936-83b08700-8ca8-11ea-99e8-1bbd0ba0ca94.png)

**Comment by zeltak** [comment]
thx for the quick response!
im using 7.1.0

<img width="338" alt="image" src="https://user-images.githubusercontent.com/498410/80896960-dcd8e480-8cc1-11ea-913c-782a7f59cc78.png">


gotta say again how impressed i am with this workflow!! really appreciate  the time you put into it as it really rocks (pun intended) ;-)

best 

Z

**Comment by caleb531** [comment]
@zeltak The way Play Song queues music is not like the Music app's "Up Next" feature. When you hold down CMD and click a result, Play Song simply adds the song (or all songs in the album, etc.) to the end of the "Alfred Play Song" playlist in the Music app. Then you can run `playqueue`in Alfred (or run `clearqueue` to start fresh).

**Comment by zeltak** [comment]
hi, hmm so know im confused :)

sorry being slow, new to the mac after 20 years of linux.. ;)

so when i issue the queue the song dosent auto play after the current, ie isn't inserted as next to play? I need to manually launch another playlist?

thx again

Z

**Comment by caleb531** [comment]
@zeltak No worries! It's not your fault, trust me.

Most everything that you play through Play Song is automatically added to a special playlist that the workflow creates (called "Alfred Play Song"), even if you're only playing a single song. So when you play or queue a song with Play Song, It gets added to the end of that same playlist. There are many reasons I've built the workflow this way, which I won't go into now.

Unfortunately (and I just tested this now), the Music app has an odd behavior whereby if you add a song to a playlist while that playlist is currently playing, music playback will stop after the song that was _originally_ last in the playlist (i.e. disregarding what you just added).

This has nothing to do with my workflow, and is just a quirk of how the Music app behaves. Sadly, there is no easy workaround.

**Comment by zeltak** [comment]
haha never mind noticed there is great documentation

> Queueing songs For any of the above filters, choosing a result with the cmd key held down > will queue the result (as opposed to playing it immediately). This allows you to queue up > multiple songs before playing them.
> To play the songs you've queued, use the playqueue keyword. To clear the queue of all songs, > use the clearqueue keyword.
> Note: At this time, Play Song does not support queueing for Apple Music playlists.


all is clear 

sorry for the noise

**Comment by caleb531** [comment]
@zeltak No worries! I always appreciate learning how people actually use my workflow.
