### ISSUE TITLE
playgenre adds songs by album and not by genre onlly

### ISSUE THREAD

**Issue by moodgorning** [caleb531/play-song#61]
It seems that if I use the playgenre keyword songs will get added on a per album basis, i.e. if at least one song in the alum fits the genre, then the whole album gets added to the playlist instead of only the songs that fit the genre. Is that intended behavior? Many thanks for the awesome workflow though.

**Comment by moodgorning** [comment]
correction, it seems to add all songs by the respective artist, not only the album

**Comment by caleb531** [comment]
@moodgorning I can reproduce the issue on my end, and will see what I can do about making `playgenre` strictly honor the genre of each song (because I agree it probably should).

**Comment by caleb531** [comment]
@moodgorning Alright, I've just pushed v8.0.0 with the fix. See the Release page to download:
https://github.com/caleb531/play-song/releases/tag/v8.0.0

Please let me know how it works for you.

**Comment by moodgorning** [comment]
Works perfect now, many thanks for the fix. And sorry I didn't  see your replies earlier.
