### ISSUE TITLE
After song ends nothing happens.

### ISSUE THREAD

**Issue by sohate** [caleb531/play-song#63]
When I turn on a song via "ps", when the song ends, the song doesn't repeat itself, despite the music app settings. Is it possible to do something so that after the end of the song turned on via "ps" the song repeat settings in the application are respected?

**Comment by caleb531** [comment]
@sohate I'm sorry, but I am unable to reproduce. Whether I enable Repeat All or Repeat One, the song _does_ repeat when the Play Song queue reaches its end. This is also the case whether I enable either Repeat mode before or after I start playback.

Are you possibly able to share a video?

**Comment by sohate** [comment]
Here's a video.

https://drive.google.com/file/d/1Jak26EofsKYKsl3-epvWnWToy2t5wnod/view?usp=sharing

**Comment by caleb531** [comment]
@sohate I see. Can you please try deleting the "Alfred Play Song" playlist within the Music app? In my experience, sometimes it gets wonky and needs to be recreated.

On your end, simply deleting it will be enough. The playlist will be automatically recreated the next time you run the workflow.

**Comment by sohate** [comment]
Did it. So far it's working. Thanks.
