### ISSUE TITLE
I have a problem that cannot be solved

### ISSUE THREAD

**Issue by westines** [caleb531/play-song#64]
![CleanShot 2021-12-09 at 12 52 57](https://user-images.githubusercontent.com/24730865/145337317-5866ec83-9b82-481e-a6cc-6c151f9fadd8.jpg)

alfred version:4.6.1
Files used：Play Song (Alfred 4).alfredworkflow

**Comment by caleb531** [comment]
@westines Try upgrading to Play Song v8.0.0; I believe I have fixed this bug for good. 🙂

https://github.com/caleb531/play-song/releases/tag/v8.0.0

**Comment by westines** [comment]
Did it. So far it's working. Thank you!
