### ISSUE TITLE
Cannot find songs outside library

### ISSUE THREAD

**Issue by Candraibra** [caleb531/play-song#66]
![image](https://github.com/caleb531/play-song/assets/30431131/02b79d6d-9663-4f7e-ab64-948cd01fc9e8)

**Comment by caleb531** [comment]
@Candraibra This workflow can only play songs/playlists that have been added to your library. 

I have looked into enhancing the workflow to search across all of Apple Music, however it can't be done in pure AppleScript, and therefore is much more involved to the point where it's not something I plan to implement.
