### ISSUE TITLE
How to stop playing?

### ISSUE THREAD

**Issue by dyang111** [caleb531/play-song#67]
Hi, thanks for the great work! I am just wondering if we have a module for stop playing song. If not, it would be super cool to have it in the futhre.

**Comment by caleb531** [comment]
@dyang111 This is already an existing Alfred feature, actually. See **Alfred Preferences > Features > Music > Keywords**.

<img width="1180" alt="Screenshot 2023-07-18 at 11 22 30 AM" src="https://github.com/caleb531/play-song/assets/872474/c5a03bc4-0203-45ea-b1ea-bffbb70531ff">
