### ISSUE TITLE
searching for songs in playlist

### ISSUE THREAD

**Issue by michaelhonein** [caleb531/play-song#70]
hi i was wondering if there was a way to specifically search for a song thats in my playlsit. That way when i do chose that song and it finishes playing my playlist continues playing as normal and doesnt give me random songs.

**Comment by caleb531** [comment]
@michaelhonein The playing of random songs after your playlist finishes might have to do with Apple Music's Autoplay feature ([details on the feature here](https://support.apple.com/guide/music/queue-up-your-songs-musb1e6d1c76/mac#musc77bceaeb)). Disabling it by toggling the little 'infinity' icon in the _Playing Next_ sidebar should stop the random songs from playing.

**Comment by michaelhonein** [comment]
but is there a way to search for a song within one of my playlists that i
created? Because when i search for a song it searches it in apple music and
not in my playlist specifically

**Comment by caleb531** [comment]
@michaelhonein Not through this workflow, specifically. But after some tinkering around, the closest you can get to jumping to a particular track in a playlist is as follows:

1. Navigate to that playlist within the Apple Music app on your Mac
2. Select the first song in the playlist
3. Start typing the name of the song you're looking for (case-insensitive, but characters like spaces and apostrophes, etc. matter). As you type, you'll see the selection update in real-time to whichever first song that matches what you've typed so far (if any)

What is the end goal you'd like to see? To play one of your playlists starting with a particular song from that playlist?

**Comment by michaelhonein** [comment]
my end goal is to be able to chose a song that i want to without losing my
playlist queue. So for example im listening to my playlist and i decide i
want to listen to a specific song on that playlist i want to be able to
search within my playlist for that song and when the song ends, the queue
is still on my playlist and it doesnt shuffle random songs. I had a spotify
mini player workflow and it could do it so thats why i was wondering if
this one can too

**Comment by caleb531** [comment]
@michaelhonein Ah I see now. Yeah, sorry, that's not possible with this workflow. The closest you could get would be to type-to-find the song within the Apple Music app, then choose the "Play Next" menu item. That would keep the rest of the playlist queued to play after that one song ends.

But since what you're describing is not specifically possible with this workflow, I am going to close the issue now.
